# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.36
#
# Don't modify this file, modify the SWIG interface instead.

package dmxinterface;
use base qw(Exporter);
use base qw(DynaLoader);
package dmxinterfacec;
bootstrap dmxinterface;
package dmxinterface;
@EXPORT = qw();

# ---------- BASE METHODS -------------

package dmxinterface;

sub TIEHASH {
    my ($classname,$obj) = @_;
    return bless $obj, $classname;
}

sub CLEAR { }

sub FIRSTKEY { }

sub NEXTKEY { }

sub FETCH {
    my ($self,$field) = @_;
    my $member_func = "swig_${field}_get";
    $self->$member_func();
}

sub STORE {
    my ($self,$field,$newval) = @_;
    my $member_func = "swig_${field}_set";
    $self->$member_func($newval);
}

sub this {
    my $ptr = shift;
    return tied(%$ptr);
}


# ------- FUNCTION WRAPPERS --------

package dmxinterface;

*initDMX = *dmxinterfacec::initDMX;
*dmxConnect = *dmxinterfacec::dmxConnect;
*dmxIsConnected = *dmxinterfacec::dmxIsConnected;
*dmxShutdown = *dmxinterfacec::dmxShutdown;
*setChannel = *dmxinterfacec::setChannel;
*peekChannel = *dmxinterfacec::peekChannel;

# ------- VARIABLE STUBS --------

package dmxinterface;

1;
